## Exercise
Using data `german_credit_data.csv` from the previous lesson, build ensemble learning models to predict credit risk.

* Import all the Python dependencies you will be needing for this exercise.

In [124]:
# YOUR CODE HERE
import pandas as pd

df = pd.read_csv('german_credit_data.csv')

* Load the dataset in a DataFrame object.

In [125]:
# YOUR CODE HERE
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
df.head()

Age     Sex  Job Housing Saving accounts Checking account  Credit amount  \
0   67    male    2     own             NaN           little           1169   
1   22  female    2     own          little         moderate           5951   
2   49    male    1     own          little              NaN           2096   
3   45    male    2    free          little           little           7882   
4   53    male    2    free          little           little           4870   

   Duration              Purpose  Risk  
0         6             radio/TV  good  
1        48             radio/TV   bad  
2        12            education  good  
3        42  furniture/equipment  good  
4        24                  car   bad

In [126]:
# DON'T WRITE HERE

* Get some statistics about the data using Panda's `describe()` and `info()` functions.

In [127]:
# YOUR CODE HERE
df.describe()

Age          Job  Credit amount     Duration
count  1000.000000  1000.000000    1000.000000  1000.000000
mean     35.546000     1.904000    3271.258000    20.903000
std      11.375469     0.653614    2822.736876    12.058814
min      19.000000     0.000000     250.000000     4.000000
25%      27.000000     2.000000    1365.500000    12.000000
50%      33.000000     2.000000    2319.500000    18.000000
75%      42.000000     2.000000    3972.250000    24.000000
max      75.000000     3.000000   18424.000000    72.000000

In [128]:
# DON'T WRITE HERE

In [129]:
# YOUR CODE HERE
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Age               1000 non-null   int64 
 1   Sex               1000 non-null   object
 2   Job               1000 non-null   int64 
 3   Housing           1000 non-null   object
 4   Saving accounts   817 non-null    object
 5   Checking account  606 non-null    object
 6   Credit amount     1000 non-null   int64 
 7   Duration          1000 non-null   int64 
 8   Purpose           1000 non-null   object
 9   Risk              1000 non-null   object
dtypes: int64(4), object(6)
memory usage: 78.2+ KB


In [130]:
# DON'T WRITE HERE

* Label encoding for columns `Sex` and `Risk`.

In [131]:
# YOUR CODE HERE
import numpy as np
df['Risk'] = np.where(df['Risk']=='bad', 1, 0)
df.head()

Age     Sex  Job Housing Saving accounts Checking account  Credit amount  \
0   67    male    2     own             NaN           little           1169   
1   22  female    2     own          little         moderate           5951   
2   49    male    1     own          little              NaN           2096   
3   45    male    2    free          little           little           7882   
4   53    male    2    free          little           little           4870   

   Duration              Purpose  Risk  
0         6             radio/TV     0  
1        48             radio/TV     1  
2        12            education     0  
3        42  furniture/equipment     0  
4        24                  car     1

In [132]:
# DON'T WRITE HERE

* Convert age to category, add to new column `Cat Age`.

In [133]:
# YOUR CODE HERE
df['Cat Age'] = pd.cut(x=df['Age'], bins=[0, 25, 30, 35, 40, 45, 50, 75])
df.head()

Age     Sex  Job Housing Saving accounts Checking account  Credit amount  \
0   67    male    2     own             NaN           little           1169   
1   22  female    2     own          little         moderate           5951   
2   49    male    1     own          little              NaN           2096   
3   45    male    2    free          little           little           7882   
4   53    male    2    free          little           little           4870   

   Duration              Purpose  Risk   Cat Age  
0         6             radio/TV     0  (50, 75]  
1        48             radio/TV     1   (0, 25]  
2        12            education     0  (45, 50]  
3        42  furniture/equipment     0  (40, 45]  
4        24                  car     1  (50, 75]

In [134]:
# DON'T WRITE HERE

* Use `get_dummies` method to make one-hot-encoding for columns: `Housing`, `Saving accounts`, `Checking account`, `Purpose` and `Cat Age`.

In [135]:
# YOUR CODE HERE
df = pd.get_dummies(df, columns=['Sex','Housing', 'Saving accounts', 'Checking account', 'Purpose', 'Cat Age'])
df.head()

Age  Job  Credit amount  Duration  Risk  Sex_female  Sex_male  \
0   67    2           1169         6     0           0         1   
1   22    2           5951        48     1           1         0   
2   49    1           2096        12     0           0         1   
3   45    2           7882        42     0           0         1   
4   53    2           4870        24     1           0         1   

   Housing_free  Housing_own  Housing_rent  ...  Purpose_radio/TV  \
0             0            1             0  ...                 1   
1             0            1             0  ...                 1   
2             0            1             0  ...                 0   
3             1            0             0  ...                 0   
4             1            0             0  ...                 0   

   Purpose_repairs  Purpose_vacation/others  Cat Age_(0, 25]  \
0                0                        0                0   
1                0                        0                1   
2                0                        0                0   
3                0                        0                0   
4                0                        0                0   

   Cat Age_(25, 30]  Cat Age_(30, 35]  Cat Age_(35, 40]  Cat Age_(40, 45]  \
0                 0                 0                 0                 0   
1                 0                 0                 0                 0   
2                 0                 0                 0                 0   
3                 0                 0                 0                 1   
4                 0                 0                 0                 0   

   Cat Age_(45, 50]  Cat Age_(50, 75]  
0                 0                 1  
1                 0                 0  
2                 1                 0  
3                 0                 0  
4                 0                 1  

[5 rows x 32 columns]

In [136]:
# DON'T WRITE HERE

* Drop unnecessary columns: `Housing`, `Saving accounts`, `Checking account`, `Purpose` and `Cat Age`.

In [137]:
# YOUR CODE HERE
# df.drop(columns=['Housing', 'Saving accounts', 'Checking account', 'Purpose', 'CatAge'])
df.head()
df.columns = df.columns.str.translate("".maketrans({"[":"{", "]":"}","<":"^"}))

# X_train.columns = X_train.columns.str.translate("".maketrans({"[":"{", "]":"}","<":"^"}))
# X_test.columns = X_test.columns.str.translate("".maketrans({"[":"{", "]":"}","<":"^"}))



In [138]:
# DON'T WRITE HERE

* Separated data as train and test (20% of data is test data, random_state=42).

In [139]:
# YOUR CODE HERE
# Segregate the features from the labels
import pandas as pd
import xgboost as xgb
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier, AdaBoostClassifier, \
    GradientBoostingClassifier, StackingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
Y = df['Risk']
X = df.drop(columns = ('Risk'))
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, shuffle=True, random_state=42)

* Apply standart scaling for `X_train` and `X_test`.

In [140]:
# YOUR CODE HERE

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
normalized_data_train = scaler.fit_transform(X_train)
normalized_data_train

normalized_data_test = scaler.fit_transform(X_test)
normalized_data_test


array([[-1.00130392,  0.27071586,  0.09750377, ..., -0.30804303,
        -0.25264558, -0.38655567],
       [-0.05748703, -1.29110641,  0.59115524, ..., -0.30804303,
        -0.25264558, -0.38655567],
       [-0.31489164,  0.27071586, -0.26132692, ..., -0.30804303,
        -0.25264558, -0.38655567],
       ...,
       [-1.34451007,  0.27071586, -0.68113808, ..., -0.30804303,
        -0.25264558, -0.38655567],
       [-0.05748703,  1.83253813,  1.6564468 , ..., -0.30804303,
        -0.25264558, -0.38655567],
       [-1.34451007,  0.27071586, -0.69399791, ..., -0.30804303,
        -0.25264558, -0.38655567]])

* Build Bagging meta-estimator model.

In [141]:
# YOUR CODE HERE
model = BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight='balanced', random_state=2),
                          random_state=2)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
# Check accuracy
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("\n")
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))
print("\n")
print("Classification report:\n", classification_report(y_test, y_pred))

Accuracy:  0.74


Confusion matrix:
 [[189  20]
 [ 58  33]]


Classification report:
               precision    recall  f1-score   support

           0       0.77      0.90      0.83       209
           1       0.62      0.36      0.46        91

    accuracy                           0.74       300
   macro avg       0.69      0.63      0.64       300
weighted avg       0.72      0.74      0.72       300



In [142]:
# DON'T WRITE HERE

* Build Random Forest model.

In [143]:
# YOUR CODE HERE
model = RandomForestClassifier(class_weight='balanced', random_state=2)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
# Check accuracy
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("\n")
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))
print("\n")
print("Classification report:\n", classification_report(y_test, y_pred))

Accuracy:  0.7233333333333334


Confusion matrix:
 [[188  21]
 [ 62  29]]


Classification report:
               precision    recall  f1-score   support

           0       0.75      0.90      0.82       209
           1       0.58      0.32      0.41        91

    accuracy                           0.72       300
   macro avg       0.67      0.61      0.62       300
weighted avg       0.70      0.72      0.70       300



In [144]:
# DON'T WRITE HERE

* Build AdaBoost model.

In [145]:
# YOUR CODE HERE
model = AdaBoostClassifier(base_estimator=DecisionTreeClassifier(class_weight='balanced', random_state=2),
                           random_state=2)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
# Check accuracy
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("\n")
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))
print("\n")
print("Classification report:\n", classification_report(y_test, y_pred))

Accuracy:  0.68


Confusion matrix:
 [[166  43]
 [ 53  38]]


Classification report:
               precision    recall  f1-score   support

           0       0.76      0.79      0.78       209
           1       0.47      0.42      0.44        91

    accuracy                           0.68       300
   macro avg       0.61      0.61      0.61       300
weighted avg       0.67      0.68      0.67       300



In [146]:
# DON'T WRITE HERE

* Build Gradient Boosting model.

In [147]:
# YOUR CODE HERE
model = GradientBoostingClassifier(learning_rate=0.01, random_state=2)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
# Check accuracy
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("\n")
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))
print("\n")
print("Classification report:\n", classification_report(y_test, y_pred))

Accuracy:  0.73


Confusion matrix:
 [[207   2]
 [ 79  12]]


Classification report:
               precision    recall  f1-score   support

           0       0.72      0.99      0.84       209
           1       0.86      0.13      0.23        91

    accuracy                           0.73       300
   macro avg       0.79      0.56      0.53       300
weighted avg       0.76      0.73      0.65       300



In [148]:
# DON'T WRITE HERE

* Build XGBoost model.

In [149]:
# YOUR CODE HERE
model = xgb.XGBClassifier(random_state=2, eta=0.01)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
# Check accuracy
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("\n")
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))
print("\n")
print("Classification report:\n", classification_report(y_test, y_pred))

Accuracy:  0.72


Confusion matrix:
 [[184  25]
 [ 59  32]]


Classification report:
               precision    recall  f1-score   support

           0       0.76      0.88      0.81       209
           1       0.56      0.35      0.43        91

    accuracy                           0.72       300
   macro avg       0.66      0.62      0.62       300
weighted avg       0.70      0.72      0.70       300



In [150]:
# DON'T WRITE HERE

* Build Stacking model.

In [151]:
# YOUR CODE HERE
estimators = [
    ('lr', LogisticRegression(class_weight='balanced', random_state=2)),
    ('knn', KNeighborsClassifier()),
    ('dt', DecisionTreeClassifier(class_weight='balanced', random_state=2)),
    ('svm', SVC(class_weight='balanced', random_state=2))
]
final_estimator = LogisticRegression(class_weight='balanced', random_state=2)
model = StackingClassifier(estimators=estimators, final_estimator=final_estimator, cv=5)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
# Check accuracy
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("\n")
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))
print("\n")
print("Classification report:\n", classification_report(y_test, y_pred))

C:\Users\nguye\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\nguye\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Accuracy:  0.6866666666666666


Confusion matrix:
 [[149  60]
 [ 34  57]]


Classification report:
               precision    recall  f1-score   support

           0       0.81      0.71      0.76       209
           1       0.49      0.63      0.55        91

    accuracy                           0.69       300
   macro avg       0.65      0.67      0.65       300
weighted avg       0.72      0.69      0.70       300



In [152]:
# DON'T WRITE HERE

* <b>Bonus</b>: Use `GridSearchCV` to find the best Hyper Parameters and re-build each model.